---
name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: 'choice'
        options:
          - 'patch'
          - 'minor'
          - 'major'
      draft:
        description: 'Create a draft release'
        required: false
        type: 'boolean'
        default: false


permissions:
  contents: write
  id-token: write
  packages: write
  attestations: write

jobs:
  create-version:
    name: Create semantic version
    runs-on: ubuntu-latest
    outputs:
      next_version: ${{ steps.next_version.outputs.next_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get the next version
        id: next_version
        run: |
          set -x

          echo "Getting current version"
          CURRENT_VERSION=$(git describe --tags --abbrev=0 || echo '0.0.0')

          echo "Current version: $CURRENT_VERSION"

          echo "Getting next version"
          # replace . with space so can split into an array
          CURRENT_VERSION_PARTS=(${CURRENT_VERSION//./ })

          # get number parts
          VNUM1=${CURRENT_VERSION_PARTS[0]}
          VNUM2=${CURRENT_VERSION_PARTS[1]}
          VNUM3=${CURRENT_VERSION_PARTS[2]}

          if [[ ${{ github.event.inputs.version }} == 'major' ]]
          then
            VNUM1=$((VNUM1+1))
          elif [[ ${{ github.event.inputs.version }} == 'minor' ]]
          then
            VNUM2=$((VNUM2+1))
          elif [[ ${{ github.event.inputs.version }} == 'patch' ]]
          then
            VNUM3=$((VNUM3+1))
          else
            echo "No version type (https://semver.org/) or incorrect type specified, try: -v [major, minor, patch]"
            exit 1
          fi

          # create new tag
          NEXT_VERSION="$VNUM1.$VNUM2.$VNUM3"

          echo "Next version: $NEXT_VERSION"
          echo "next_version=$NEXT_VERSION" >> $GITHUB_OUTPUT

  release:
    runs-on: ubuntu-latest
    needs: create-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: sigstore/cosign-installer@v4
      - uses: anchore/sbom-action/download-syft@v0

      - name: Log in to docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create tag
        run: |
          echo "Creating tag and pushing"
          git config --local user.email "github@action.com"
          git config --local user.name "GitHub Action"
          git tag -a ${{ needs.create-version.outputs.next_version }} -m "Release ${{ needs.create-version.outputs.next_version }}"
          git push origin ${{ needs.create-version.outputs.next_version }}
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: ~> v2
          args: release ${{ github.event.inputs.draft == 'true' && '--draft' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/attest-build-provenance@v3
        with:
          subject-checksums: ./dist/checksums.txt
      - uses: actions/attest-build-provenance@v3
        with:
          subject-checksums: ./dist/digests.txt
